--
-- Estrutura da tabela AFL_TBL_ATORES
--

CREATE TABLE AFL_TBL_ATORES (
  IN_ID_AUTOR int NOT NULL IDENTITY ,
  TX_PRIMEIRO_NOME VARCHAR(45) NOT NULL,
  TX_ULTIMO_NOME VARCHAR(45) NOT NULL,
  DT_ULTIMA_ATUALIZACAO DATETIME NOT NULL,
  PRIMARY KEY NONCLUSTERED (IN_ID_AUTOR)
  )
GO
 ALTER TABLE AFL_TBL_ATORES ADD CONSTRAINT [DF_AFL_TBL_ATORES_DT_ULTIMA_ATUALIZACAO] DEFAULT (getdate()) FOR DT_ULTIMA_ATUALIZACAO
GO
 CREATE  INDEX IDX_AFL_TBL_ATORES_TX_ULTIMO_NOME ON AFL_TBL_ATORES(TX_ULTIMO_NOME) 
GO